dist: bionic

language: go
go:
  - 1.14.x

env:
  - GO111MODULE="on"

before_install:
  - sudo apt-get install -y libseccomp-dev containerd

install:
  - sudo curl -fSL "https://github.com/genuinetools/netns/releases/download/v0.5.3/netns-linux-amd64" -o /usr/local/bin/netns
  - sudo chmod a+x /usr/local/bin/netns
  - pushd $GOPATH && go get github.com/onsi/ginkgo/ginkgo && popd
  - pushd $GOPATH && env GO111MODULE=off go get github.com/onsi/gomega/... && popd
  - go build ./...
  - ./getruntimes/download_runtimes.sh

script: sudo env "PATH=$PATH" ginkgo -r --randomizeAllSpecs --randomizeSuites -nodes=2
