dist: xenial
sudo: required

language: go
go:
  - 1.11.x
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - sudo apt-get install -y libseccomp-dev

install:
  - wget -qO - https://packages.confluent.io/deb/5.2/archive.key | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.2 stable main"
  - sudo apt-get install -y librdkafka-dev
  - wget https://github.com/containerd/containerd/releases/download/v1.2.2/containerd-1.2.2.linux-amd64.tar.gz
  - tar -xvf containerd-1.2.2.linux-amd64.tar.gz
  - export PATH=$PATH:$PWD/bin/
  - go get github.com/opencontainers/runc
  - pushd $GOPATH/src/github.com/opencontainers/runc && make && sudo make install && popd
  - sudo curl -fSL "https://github.com/genuinetools/netns/releases/download/v0.5.3/netns-linux-amd64" -o /usr/local/bin/netns
  - sudo chmod a+x /usr/local/bin/netns
  - go get -v ./...
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega/...
  - export PATH=$PATH:$HOME/gopath/bin
  - ./getruntimes/download_runtimes.sh

script: sudo env "PATH=$PATH" ginkgo -r --randomizeAllSpecs --randomizeSuites
