# poolsize = 8
# runtime = "python"
# target_layer = "serverless-function.py"

[[poolgroup]]
size = 1
runtime = "python"
target_layer = "serverless-function.py"

[[poolgroup]]
size = 1
runtime = "java"
target_layer = "serverless-java"

[[poolgroup]]
size = 1
runtime = "node"
target_layer = "serverless-function.js"

[kafka]
# address = "somekafkaaddr"

[couch]
# address = "somecouchaddr"
# activation_db = "test_activations"
# function_db = "test_whisks"
